### PR TITLE
storage: fix incorrect API scopes for IAM SignBlob API

### LINKED ISSUE #599: Fog::Storage::GoogleJSON::Real#iam_signer is using the wrong API scopes with Workload Identity
I was investigating why running GitLab in Kubernetes with Workload Identity instead of a service account key resulted in `ACCESS_TOKEN_SCOPE_INSUFFICIENT` errors:

```ruby
irb(main):045:0> credentials = {provider: 'Google', google_project: 'my-gitlab-project', google_application_default: true}
=> {:provider=>"Google", :google_project=>"my-gitlab-project", :google_application_default=>true}
irb(main):046:0> raw_config = {enabled: true, connection: credentials, remote_directory: 'my-gitlab-project-uploads', storage_options: {}, consolidated_settings: false}
=>
{:enabled=>true,
...
irb(main):047:0> config = ObjectStorage::Config.new(raw_config)
=>
#<ObjectStorage::Config:0x00007f3d35837538
...
irb(main):048:0> du = ObjectStorage::DirectUpload.new(config, 'tmp/foo/bar', has_length: true)
=>
#<ObjectStorage::DirectUpload:0x00007f3d35fdbc58
...
irb(main):049:0> du.get_url rescue puts $!.body
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.iam.credentials.v1.IAMCredentials.SignBlob",
          "service": "iamcredentials.googleapis.com"
        }
      }
    ]
  }
}
=> nil
```

Digging into `fog-google` I have found 2 issues causing this:

1. `Fog::Storage::GoogleJSON::Real#iam_signer` is using the wrong API scope, it should be `https://www.googleapis.com/auth/iam` instead of `https://www.googleapis.com/auth/devstorage.full_control`: https://github.com/fog/fog-google/blob/30685949ff7688e1066e4c8625480caffc7a495f/lib/fog/storage/google_json.rb#L32
2. Fixing the API scope above alone is not enough, as `Fog::Storage::GoogleJSON::Real#iam_signer` seems to be re-using the same session and auth credentials as with the storage operations, I haven't been able to find where and why yet but changing `GOOGLE_STORAGE_JSON_API_SCOPE_URLS`  to `https://www.googleapis.com/auth/cloud-platform` did indeed make it work, though that's not the ideal solution

### PR DESCRIPTION
**Pull request by stanhu**
Previously when a service account attempted to use the IAM SignBlob API, the request would fail with a 403
`ACCESS_TOKEN_SCOPE_INSUFFICIENT` because the wrong scope was requested.

As documented in
https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signBlob, either `https://www.googleapis.com/auth/iam` or
`https://www.googleapis.com/auth/cloud-platform` is needed.

This commit fixes an issue where the default authorization header with the `https://www.googleapis.com/auth/devstorage.full_control` scope was being used by the IAM service. This occurred because the previous code did not actually set the scope properly, and for the IAM service to work properly, we need to request a new access token with the correct scope.

Note that the service account in question needs to have the `Service Account Token Creator` IAM role to work.

Closes #599

### CODE REVIEW

File: lib/fog/storage/google_json/real.rb [hunk 1]
```diff
@@ -10,16 +10,12 @@ class Real
 
         def initialize(options = {})
           shared_initialize(options[:google_project], GOOGLE_STORAGE_JSON_API_VERSION, GOOGLE_STORAGE_JSON_BASE_URL)
+          @options = options.dup
           options[:google_api_scope_url] = GOOGLE_STORAGE_JSON_API_SCOPE_URLS.join(" ")
           @host = options[:host] || "storage.googleapis.com"
 
           # TODO(temikus): Do we even need this client?
```
Comment (stanhu) [inline lib/fog/storage/google_json/real.rb:17]: I was tempted to drop this and `@client` since they're not actually used.

File: lib/fog/storage/google_json/real.rb [hunk 2]
```diff
@@ -141,6 +137,18 @@ def default_signer(string_to_sign)
...
         end
 
+        # IAM client used for SignBlob API.
+        # Lazily initialize this since it requires another authorization request.
+        def iam_service
+          return @iam_service if defined?(@iam_service)
+
+          @iam_service = ::Google::Apis::IamcredentialsV1::IAMCredentialsService.new
+          apply_client_options(@iam_service, @options)
+          iam_options = @options.merge(google_api_scope_url: GOOGLE_STORAGE_JSON_IAM_API_SCOPE_URLS.join(" ")))
```
Comment (stanhu) [inline lib/fog/storage/google_json/real.rb:147]: In the future, it might be nicer to distinguish between options that are only used by this gem and options that are used by the Google SDK. It's not obvious that `google_api_scope_url` isn't passed all the way to the Google SDK.

**Comment by stanhu** [comment]
@Temikus Would you mind reviewing this? This seems to be a pretty critical fix for Google Kubernetes Engine users.

File: lib/fog/storage/google_json.rb [hunk 3]
```diff
@@ -29,7 +29,7 @@ class GoogleJSON < Fog::Service
 
       # Version of IAM API used for blob signing, see Fog::Storage::GoogleJSON::Real#iam_signer
       GOOGLE_STORAGE_JSON_IAM_API_VERSION = "v1".freeze
-      GOOGLE_STORAGE_JSON_IAM_API_SCOPE_URLS = %w(https://www.googleapis.com/auth/devstorage.full_control).freeze
+      GOOGLE_STORAGE_JSON_IAM_API_SCOPE_URLS = %w(https://www.googleapis.com/auth/iam).freeze
```
Comment (stanhu) [inline lib/fog/storage/google_json.rb:32]: @peikk0 Should we use https://www.googleapis.com/auth/cloud-platform instead?

Comment (stanhu) [reply lib/fog/storage/google_json.rb:32]: https://www.googleapis.com/auth/cloud-platform seems much more permissive. I'm inclined to stick with this?

Comment (peikk0) [reply lib/fog/storage/google_json.rb:32]: On one hand, `https://www.googleapis.com/auth/iam` is more restrictive and keeps the original intent. On the other hand, access scopes are considered legacy by Google and they recommend using `https://www.googleapis.com/auth/cloud-platform` and proper IAM permissions instead: https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam But changing to that could have security implications for users that still rely on it so it might be safer to stick to `https://www.googleapis.com/auth/iam` for now.

Comment (stanhu) [reply lib/fog/storage/google_json.rb:32]: 👍 Thanks!

File: lib/fog/storage/google_json/real.rb (hunk 1 above)
Comment (Temikus) [reply lib/fog/storage/google_json/real.rb:17]: You use this API more than me so I am happy to drop this if there are no corner cases here 👍

**Review by Temikus — APPROVED** [review]
LGTM - feel free to drop the client too

**Comment by Temikus** [comment]
And thanks for your contributions @stanhu as usual ❤️

File: lib/fog/storage/google_json/real.rb (hunk 1 above)
Comment (stanhu) [reply lib/fog/storage/google_json/real.rb:17]: Let's leave this in for now.

**Comment by Temikus** [comment]
Kicked off the CI, once it passes will merge and release as soon as I can.

**Comment by Temikus** [comment]
@stanhu looks like there’s a small typo causing some errors - you can see the unit test run failing ‘rake test:unit’ for local if you need it.

**Comment by stanhu** [comment]
> @stanhu looks like there’s a small typo causing some errors - you can see the unit test run failing ‘rake test:unit’ for local if you need it.

Thanks. That was a last-minute refactor, should be fixed now.

**Comment by Temikus** [comment]
LGTM, merging 👍 Will aim to release today if I can - if not - will push Friday.
