### PR TITLE
Fix bug where listing of bucket causes infinite loop

### LINKED ISSUE #151: JSON Storage stack overflow when calling files.all()
Maybe I'm doing something wrong, but if I create a bucket and attempt to list files within, the system appears to get stuck in a loop until the stack is exhausted.

Steps to recreate (from HEAD):

```
irb(main):001:0> g = Fog::Storage::Google.new
=> [...]
irb(main):002:0> g.directories.create(key: 'example-fog-bucket').files
# repl hangs here, slowly exhausting stack
```

### PR DESCRIPTION
**Pull request by selmanj**
Closes #151 

Guys, I'm not sure that the json storage implementation is working; I couldn't find an implementation of `list_objects` and had to add one, and the file/directory abstractions contain a lot of stuff that doesn't match to the json api (hence the addition of the `name` alias change below in `file.rb`).

I'm trying to make this change as minor as possible in order to fix the bug, but I think it might be beneficial to revisit the entire storage json implementation.

### CODE REVIEW

File: lib/fog/storage/google_json/requests/list_objects.rb [hunk 1]
```diff
@@ -0,0 +1,50 @@
+module Fog
```
Comment (selmanj) [inline lib/fog/storage/google_json/requests/list_objects.rb]: Sorry, I'm not following you here, bot. Anyone know what he wants me to `freeze`?

**Comment by erjohnso** [comment]
Looks like this was modeled after closely with fog-aws:
- Model matches: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/storage/files.rb
- No list_objects request: https://github.com/fog/fog-aws/tree/master/lib/fog/aws/requests/storage

That said, as long is the functionality matches S3 (but works!), I think this is fine.

I don't know why your houndci is complaining. :(

**Comment by Temikus** [comment]
IIRC there's also a need to be cross-compatible with Paperclip/CarrierWave. And AFAIK Paperclip works pretty well.

Thanks for the patch, I'll take this review, just give me a day or two, things are a bit hectic at the moment.

**Comment by selmanj** [comment]
@Temikus Looking at both packages, it looks like they're both coded against the generic directories api. Paperclip doesn't give any examples on how to setup Google integration, but CarrierWave says to use S3 credentials via:

```ruby
CarrierWave.configure do |config|
  config.fog_provider = 'fog/google'                        # required
  config.fog_credentials = {
    provider:                         'Google',
    google_storage_access_key_id:     'xxxxxx',
    google_storage_secret_access_key: 'yyyyyy'
  }
  config.fog_directory = 'name_of_directory'
end
```

If someone has setup their fog client using the `google_storage_access_key_id`, then they will always use the XML interface for storage, not the JSON, as shown here: 
```ruby
module Fog
  module Storage
    class Google < Fog::Service
      def self.new(options = {})
        begin
          fog_creds = Fog.credentials
        rescue
          fog_creds = nil
        end

        if options.keys.include?(:google_storage_access_key_id) ||
           (!fog_creds.nil? && fog_creds.keys.include?(:google_storage_access_key_id))
          Fog::Storage::GoogleXML.new(options)
        else
          Fog::Storage::GoogleJSON.new(options)
        end
      end
    end
  end
end
```
Basically, if someone has setup their client to use storage credentials, then they're not using the JSON implementation (the XML implementation likely works fine). Also note this change isn't changing anything in the interface; instead I'm merely trying to make the interface work.

File: lib/fog/storage/google_json/requests/list_objects.rb (hunk 1 above)
Comment (Temikus) [inline lib/fog/storage/google_json/requests/list_objects.rb]: @selmanj 
`# frozen_string_literal: true` is a magic comment, supported for the first time in Ruby 2.3, that tells Ruby that all string literals in the file are implicitly frozen. The comment must be on the first line of the file. It will be the default in Ruby3, so it's a way to test out the transition from 2.3 onwards.

I would avoid this for now as this needs to be added and tested en-masse.

Thanks for pointing this out, I'll disable the cop for now.

**Comment by Temikus** [comment]
@selmanj I'm aware, I'm the one who reviewed that logic ;)

But AFAIK if one specifies the JSON credentials only, it should "just work"(TM) with Paperclip.
Not that sure about CarrierWave, I'll need to test that out.

And I get that you're only fixing the interface and I'm _extremely_ thankful for that. I want to just make sure we return the proper object from the get go, so we don't have to deprecate anything later.

**Comment by Temikus** [comment]
LGTM, thank you so much Joe!

**Comment by selmanj** [comment]
Awesome, thanks!
